import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 20,
    },
    handleContainer: {
        paddingVertical: 12,
        alignItems: 'center',
    },
    handle: {
        width: 48,
        height: 4,
        backgroundColor: '#E0E0E0',
        borderRadius: 2,
    },
    content: {
        paddingHorizontal: 20,
        paddingBottom: 32,
    },
    
    //   Estilos para vista minimizada
    minimizedView: {
        paddingBottom: 8,
    },
    minimizedHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    minimizedIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#4285F4',
        justifyContent: 'center',
        alignItems: 'center',
    },
    minimizedInfo: {
        flex: 1,
    },
    minimizedDestination: {
        fontSize: 16,
        fontWeight: '700',
        color: '#202124',
        marginBottom: 4,
    },
    minimizedStats: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    minimizedStat: {
        fontSize: 13,
        color: '#5F6368',
        fontWeight: '500',
    },
    minimizedDivider: {
        fontSize: 13,
        color: '#DDD',
    },
    minimizedPulse: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#34A853',
    },
    
    // Estilos existentes
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    iconContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#E8F0FE',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    headerText: {
        flex: 1,
    },
    title: {
        fontSize: 13,
        color: '#5F6368',
        marginBottom: 2,
        fontWeight: '500',
    },
    destination: {
        fontSize: 18,
        fontWeight: '700',
        color: '#202124',
        letterSpacing: -0.3,
    },
    infoContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 20,
    },
    infoCard: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8EAED',
    },
    iconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    infoLabel: {
        fontSize: 11,
        color: '#5F6368',
        marginBottom: 4,
        fontWeight: '500',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    infoValue: {
        fontSize: 20,
        fontWeight: '700',
        color: '#202124',
        letterSpacing: -0.5,
    },
    recalculatingBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E8F0FE',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 16,
        gap: 10,
    },
    recalculatingText: {
        fontSize: 14,
        color: '#4285F4',
        fontWeight: '600',
    },
    buttonContainer: {
        gap: 12,
    },
    startButton: {
        backgroundColor: '#4285F4',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 8,
        shadowColor: '#4285F4',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    startButtonDisabled: {
        backgroundColor: '#93B4E8',
        opacity: 0.7,
    },
    startButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    pulseIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#34A853',
        marginRight: 4,
    },
    closeButton: {
        backgroundColor: 'transparent',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 12,
        gap: 6,
        borderWidth: 1.5,
        borderColor: '#E8EAED',
    },
    closeButtonText: {
        color: '#5F6368',
        fontSize: 15,
        fontWeight: '600',
    },
});